project/api/urls.py
from rest_framework import routers

from django.urls import path, include, re_path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from api.views import NewsAPIList, NewsAPIDelete, NewsAPIUpdate, NewsViewSet

router = routers.SimpleRouter()
router.register(r'api/v1/news/', NewsViewSet, basename='news')

# print(router.urls)

urlpatterns = [
    path('api/v1/news/', NewsAPIList.as_view()),
    path('api/v1/news/<int:pk>/', NewsAPIUpdate.as_view()),
    path('api/v1/news_delete/<int:pk>/', NewsAPIDelete.as_view()),

    # маршруты, сгенерированные роутером
    # path('', include(router.urls)),

    # с этим маршрутом становится доступна Session-based аутентификация
    # также в UI появляется кнопка login/logout
    path('api-auth/', include('rest_framework.urls')),


    # маршруты для работы аутентификации на базе обычных токенов
    # для авторизации в Postman нужно добавить заголовок Authorization со значением "Token <token>"
    # токен генерируется на странице http://127.0.0.1:8000/auth/token/login
    # также для генерации токена на адрес выше можно отправить post-запрос:
    # {
    #     "username": "tokenuser",
    #     "password": "1234user"
    # }
    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),

    # маршруты для работы аутентификации на базе JWT-токенов (Json Web Tokens)
    # для авторизации в Postman нужно добавить заголовок Authorization со значением "Bearer <token>"
    # токен генерируется на странице http://127.0.0.1:8000/api/v1/jwt_auth/
    # также для генерации токена на адрес выше можно отправить post-запрос (нужно использовать access-часть токена!):
    # {
    #     "username": "tokenuser",
    #     "password": "1234user"
    # }
    # https://www.youtube.com/watch?v=b4C6UTlSC-o&t=4s&ab_channel=selfedu
    path('api/v1/jwt_auth/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # подключаем маршруты API
    path('', include('api.urls')),
]

if settings.DEBUG:

    # если дебаг-тулбар не работает, нужно пофиксить значение в реестре: https://www.youtube.com/watch?v=1LrWRY_buxE&ab_channel=Nu_Leh
    # ИЛИ добавить
    # import mimetypes
    # mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/newsapp/models.py
from django.db import models
from django.db.models import CheckConstraint, Q, F
from django.urls import reverse
from django.contrib.auth.models import User

# http://127.0.0.1:8000/admin/


class Category(models.Model):
    title = models.CharField(max_length=150, verbose_name='Категория')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        kwargs = {
            # 'category_id': self.id,
            'category_slug': self.slug
        }

        # имя маршрута и аргументы
        # их надо прописывать в соответствии с именами маршрута и аргументов в urls.py
        return reverse('news_by_category_route', kwargs=kwargs)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        # '-' перед полем укажет на обратный порядок сортировки
        ordering = ['title']


class News(models.Model):
    # db_column - переопределяем имя поля в БД
    # id = models.IntegerField(primary_key=True, db_column='id', verbose_name='Идентификатор')
    title = models.CharField(max_length=150)
    # blank = True - может принимать пустое значение
    content = models.TextField()
    created_at = models.DateTimeField(null=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, auto_now=True)
    # upload_to - директория загрузки
    # можно переделать поле на imagePath и написать свою логику загрузки
    image = models.ImageField(upload_to='images/%Y/%m/%d/', null=True, blank=True)
    # default - значение по умолчанию
    is_published = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, db_column='category_id')
    views_count = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    # строковое представление для корректного отображения в админке
    def __str__(self):
        return self.title

    # специальный подкласс для кастомизации админки
    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        # '-' перед полем укажет на обратный порядок сортировки
        ordering = ['-created_at']

    def get_absolute_url(self):
        kwargs = {
            'news_id': self.id
        }
        return reverse('one_news_route', kwargs=kwargs)


class Like(models.Model):
    news = models.ForeignKey(News, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки'
        ordering = ['user']
        constraints = [
            models.UniqueConstraint(fields=['user', 'news'], name='unique_constraint')
        ]

project/templates/add_news.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

<h1> Добавление новости </h1>

{# ФОРМА И СПОСОБЫ ЕЕ РЕНДЕРИНГА #}
<form action="{% url 'add_news_route' %}" method="post" enctype="multipart/form-data">

    {% csrf_token %}

    {# СПОСОБ 1. АВТОРЕНДЕРИНГ #}
    {{ form.as_p }}

    {% comment %}
    {# СПОСОБ 2. РЕНДЕРИНГ КАЖДОГО ОТДЕЛЬНОГО ПОЛЯ ВРУЧНУЮ. нужен, если надо задать уникальную разметку для полей #}
    {{ form.non_field.errors }}
    <div class="form-group">

        <label for="{{ form.title.id_for_label }}">Название</label>
        {{ form.title }}

        <div class="invalid-feedback">
            {{ form.title.errors }}
        </div>

    </div>

    <div class="form-group">

        <label for="{{ form.content.id_for_label }}">Текст</label>
        {{ form.content }}

        <div class="invalid-feedback">
            {{ form.content.errors }}
        </div>

    </div>

    <div class="form-group">

        <label for="{{ form.is_published.id_for_label }}">Опубликовано?</label>
        {{ form.is_published }}

        <div class="invalid-feedback">
            {{ form.is_published.errors }}
        </div>

    </div>

    <div class="form-group">

        <label for="{{ form.category.id_for_label }}">Категория</label>
        {{ form.category }}

        <div class="invalid-feedback">
            {{ form.category.errors }}
        </div>

    </div>
    {% endcomment %}

    {% comment %}
    {# СПОСОБ 3. ПОЛУАВТОМАТИЧЕСКИЙ РЕНДЕР #}
    {% for field in form %}
    <div class="form-group">

        {{ field.label_tag }}
        {{ field }}

        <div class="invalid-feedback">
            {{ field.errors }}
        </div>

    </div>
    {% endfor %}
    {% endcomment %}

    <button type="submit" class="btn btn-primary btn-block">
        Добавить новость
    </button>

</form>

{% endblock %}

project/templates/auth_token.html
{% extends 'base.html' %}

{% block title %}
Auth token generate
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}

<h1> Auth token generate </h1>

<form method="post">

    {% csrf_token %}

    {# авторендеринг формы #}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary btn-block">
        Generate
    </button>

</form>

{% endblock %}

project/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} {% endblock %} </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

</head>

<body>

{% include 'inc/_navbar.html' %}

<div class="container mt-3">

    <div class="row">

        <div class="col-md-3">
            {% block sidebar %} NOT IMPLEMENTED SIDEBAR BLOCK {% endblock %}
        </div>

        <div class="col-md-9">

            {% if messages %}

            {% for msg in messages %}

                {% if msg.tags == 'error' %}
                    <div class="alert alert-danger" role="alert">
                        {{ msg }}
                    </div>
                {% else %}
                    <div class="alert alert-{{ msg.tags }}" role="alert">
                        {{ msg }}
                    </div>
                {% endif %}

            {% endfor %}

            {% endif %}

            {% block content %} NOT IMPLEMENTED CONTENT BLOCK {% endblock %}

            {% if page_obj.has_other_pages %}
                {% include 'inc/_paginator.html' %}
            {% endif %}

        </div>

    </div>

</div>

</body>

</html>

project/templates/categories_list.html
<div class="list-group">

    {% for category in categories %}
    <a href="{{ category.get_absolute_url }}" class="list-group-item list-group-item-action"> {{ category.title }}
        <span class="badge rounded-pill text-bg-primary"> {{ category.count }} </span>
    </a>
    {# альтернатива для get_absolute_url (get_absolute_url более хороший варик - {% url 'news_by_category_route' category.title %} #}

    {% endfor %}
</div>

project/templates/edit_news.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

<h1> Редактирование новости </h1>

<form action="" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
<!--    {{ form.as_p }}-->

    <input type="hidden" name="csrfmiddlewaretoken" value="p8geqPqCqoF6qPo9T6u3wZ3jSaJEMbJUB2Ys1Yp3M42cG2ERsiDzky3itarHNlWq">

    <p>
        <label for="id_title">Название:</label>
        <input type="text" name="title" class="form-control" maxlength="150" required="" id="id_title" value="{{ news_obj.title }}">
    </p>

    <p>
        <label for="id_content">Текст новости:</label>
        <textarea name="content" cols="40" rows="5" class="form-control" required="" id="id_content">
            {{ news_obj.content }}
        </textarea>
    </p>


    <p>
        <label for="id_is_published">Опубликовано?</label>
        <input type="checkbox" name="is_published" id="id_is_published"
               {% if news_obj.is_published %}
               checked="checked"
               {% endif %}
        />
    </p>

    <p>
        <label for="id_category">Категория:</label>

        <select name="category" class="form-control" id="id_category">
            {% for category in categories %}
            <option {% if news_obj.category == category %} selected {% endif %} value="{{ category.pk }}">{{ category.title }}</option>
            {% endfor %}
        </select>
    </p>


    <p>
        <label for="id_image">Image:</label>
        <input type="file" name="image" accept="image/*" id="id_image">
    </p>

    <button type="submit" class="btn btn-primary btn-block">
        Сохранить
    </button>

</form>

{% endblock %}

project/templates/jwt_token.html
{% extends 'base.html' %}

{% block title %}
JWT token generate
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}

<h1> JWT token generate </h1>

<form method="post">

    {% csrf_token %}

    {# авторендеринг формы #}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary btn-block">
        Generate
    </button>

</form>

{% endblock %}

project/templates/login.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

<h1> Войти </h1>

<form method="post">

    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary btn-block">
        Войти
    </button>

</form>

{% endblock %}

project/templates/news_by_category.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

    {% for news_item in news %}

    <div class="card mb-3">

        <div class="card-header">
            Категория: {{ news_item.category }}
        </div>

        <div class="card-body">
            <div class="media d-flex">

                {% if news_item.image %}
                <img src="{{ news_item.image.url }}" alt="" height="300" width="300" class="me-3">
                {% else %}

                {% endif %}

                <div class="media-body">
                    <h5 class="card-title"> {{ news_item.title|safe }} </h5>
                    <p class="card-text"> {{ news_item.content|safe|truncatewords:50 }} </p>
                    <a href="{{ news_item.get_absolute_url }}" class="btn btn-primary"> Read more... </a>
                </div>

            </div>


        </div>

        <div class="card-footer text-muted">
            {{ news_item.user }}, {{ news_item.created_at|date:"Y-m-d H:i" }}
            <span style="float:right" class="badge rounded-pill text-bg-primary"> {{ news_item.views_count }} views </span>
        </div>

    </div>

    {% endfor %}

{% endblock %}

project/templates/news_list.html
{% extends 'base.html' %}

<! -- выводим тайтл из передаваемой в контексте переменной title
и тайтл из базового темплейта -->

{% block title %}
    {{ title }} {{ block.super }}
{% endblock %}

{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

    {% for news_item in news %}
    <div class="card mb-3">

        <div class="card-header">
            <a href="{{ news_item.category.get_absolute_url }}" class="list-group-item list-group-item-action"> Категория: {{ news_item.category }} </a>
        </div>

        <div class="card-body">
            <div class="media d-flex">

                {% if news_item.image %}
                <img src="{{ news_item.image.url }}" alt="" height="300" width="300" class="me-3">
                {% else %}

                {% endif %}

                <div class="media-body">
                    <h5 class="card-title"> {{ news_item.title|safe }} </h5>
                    <p class="card-text"> {{ news_item.content|safe|truncatewords:50 }} </p>
                    <a href="{{ news_item.get_absolute_url }}" class="btn btn-primary"> Read more... </a>
                </div>

            </div>


        </div>

        <div class="card-footer text-muted">
            {{ news_item.user }}, {{ news_item.created_at|date:"Y-m-d H:i" }}
            <span style="float:right" class="badge rounded-pill text-bg-primary"> {{ news_item.views_count }} views </span>
        </div>

    </div>
    {% endfor %}

{% endblock %}

project/templates/news_page.html
{% extends 'base.html' %}

<! -- выводим тайтл из передаваемой в контексте переменной title
и тайтл из базового темплейта -->

{% block title %}
{{ news_item.title }}
{% endblock %}

{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

<div class="card mb-3">

    <div class="card-header">
        <a href="{{ news_item.category.get_absolute_url }}" class="list-group-item list-group-item-action"> Категория: {{ news_item.category }} </a>
    </div>

    <div class="card-body">

        {# <div class="media d-flex"> #}

        {% if news_item.image %}
        <img src="{{ news_item.image.url }}" alt="" height="300" width="300" class="float-start me-3">
        {% else %}

        {% endif %}

        {# <div class="media-body"> #}
            <h5 class="card-title"> {{ news_item.title|safe }} </h5>
            <p class="card-text"> {{ news_item.content|safe }} </p>
            {# </div> #}

        {# </div> #}

        {% if request.user == news_item.user or user.is_staff %}

        <form action="{% url 'delete_news_route' pk=news_item.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger float-end">Удалить новость</button>
        </form>

        <form action="{% url 'edit_news_route' pk=news_item.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-primary">Редактировать новость</button>
        </form>

        {% endif %}

    </div>

    <div class="card-footer text-muted">
        {{ news_item.user }}, {{ news_item.created_at|date:"Y-m-d H:i" }}
        <span style="float:right" class="badge rounded-pill text-bg-primary"> {{ news_item.views_count }} views </span>
    </div>

</div>

{% endblock %}

project/templates/register.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block sidebar %}
{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

<h1> Регистрация </h1>

<form method="post">

    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary btn-block">
        Подтвердить
    </button>

</form>

{% endblock %}